nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        tags:
        - name: "Shops"
          description: "Operations about shops"
        - name: "Technical test"
          description: "Call api les-habitues"
    areas:
        default:
            path_patterns: [ /les-habitues/ ]